### PR TITLE
Update V2.1 Changelog

### LINKED ISSUE #266: Temperature Anomalies - Apparent Temperature was 178,423°F
### Describe the bug

On multiple occasions recently, the apparent hi/lo temps have been inaccurate by a significant order of magnitude.

image

The issue first appeared on 2024-07-11 at 11:35:00 UTC.

### Expected behavior

I expect the weather forecast data to be within a reasonable range.

### Actual behavior

The weather forecast data said that my backyard was 10x hotter than the surface of the sun.

### API Endpoint

Production

### Location

Chicago, IL, US

### Other details

_No response_

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #281: Current summary and icon sometimes returning `none`
### Describe the bug

In recent days I have been experiencing repeated appearances of the `exceptional` state. Checking on merrysky it does not turn out to be anything particularly out of the ordinary

### Expected behavior

See an analogue to the conditions shown by other PW-based 

### Actual behavior

e.g. exactly now it is shown exceptional when the condition is trivially partly cloudy
(`eccezionale` mean `exceptional`)
image
image

### Home Assistant version

2024.7.4

### Integration version

1.5.2

### Other details

Unfortunately, the `exceptional` condition is poorly documented but browsing the core code [these](https://github.com/home-assistant/core/blob/537d7728a726816220be0ca7c7f68ecea7d835d1/homeassistant/components/nws/const.py#L34) seem to be the conditions that fall under the term `exceptional`

> ```py
> #...
> CONDITION_CLASSES: dict[str, list[str]] = {
>     ATTR_CONDITION_EXCEPTIONAL: [
>         "Tornado",
>         "Hurricane conditions",
>         "Tropical storm conditions",
>         "Dust",
>         "Smoke",
>         "Haze",
>         "Hot",
>         "Cold",
>     ],
> #...
> ```

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

### LINKED ISSUE #283: Pressure has extreme values (like -308024647.68 or 151026579537.92) at some point of the forecast
### Describe the bug

A pressure runs into extreme positive and negative values (so large that my uint32 encoding fails).
I can see it happening right now (timestamp 1723022370 or `2024-08-07T09:19:30+00:00`)

Request: https://api.pirateweather.net/forecast/<api token>/38.631,-105.071?exclude=currently,minutely,daily,alerts,flags&extend=hourly&units=si&version=2

Also visible on Merry Sky: https://merrysky.net/forecast/38.631,-105.071/ca

image

### Expected behavior

The pressure should have expected values

### Actual behavior

The pressure have values exceeding uint32 in both positive and negative values at some point in the forecast

### API Endpoint

Production

### Location

38.631,-105.071

### Other details

_No response_

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #284: Pressure reading jumps to 3000 mbar at midnight
### Describe the bug

I'm using Home Assistant but there have been no changes that I know of in that area. Since a week or so the pressure value jumps exactly at midnight to 3000 and then it recovers.

image

### Expected behavior

Pressure should have a reasonable value.

### Actual behavior

Pressure jumps to 3000 mbar

### API Endpoint

Production

### Location

Timisoara, Romania

### Other details

_No response_

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #289: Extreme spikes / outliers in temperature
Did I post in the wrong repo?
https://github.com/Pirate-Weather/pirateweather/issues/283 Related?
Let me know.

### Describe the bug

image

This happens every few weeks. A lot more recently though.

### Expected behavior

I don't know what the data source is and how this is processed, but can this be filtered out? A filter in pirate weather that drops these extreme values?

### Actual behavior

These extreme values seem to happen mostly around midnight.

They immediately disturb the graph view in HA as shown above. Any detail is lost by this hit of 600 degrees C. And of course, automations related to opening/closing windows, enabling heating/cooling, based on the temperature outside are failing.

### Home Assistant version

2024.6.4

### Integration version

1.5.3

### Other details

Yes, sorry, I am on an 'old' version of HA. I cannot afford down time, bugs or issues in the household and therefore lack behind in version. (See for example big issues in the 7 release of this year. https://community.home-assistant.io/t/2024-7-time-to-resize-your-cards/745771.)

The report about the issue I am making here has been happening for months. There should not be a relationship with the HA version. I did check the release notes of 2024.7 and 2024.8 and have not found anything that could be related to this issue.

### Troubleshooting steps

- [X] I have updated my Home Assistant installation to the latest version.
- [X] I have updated the Pirate Weather Integration to the latest version.
- [X] I have gone through the [documentation](https://pirateweather.net/en/latest/ha/) before opening this issue.
- [X] I have searched this repository and [API Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have restarted my Home Assistant installation.
- [X] I have queried the API in my browser to confirm the issue is not with the API.
- [X] I have written an informative title.

### PR DESCRIPTION
**Pull request by cloneofghosts**
Updated the V2.1 changelog for the fix which wasn't included in the PR which was merged last night.

* Fix #281
* Fix #289
* Fix #266
* Fix #283 
* Fix #284 
* It also should address the issues seen in #229

### CODE REVIEW

**Comment by cloneofghosts** [comment]
@alexander0042 I guess you can think of this as your reminder to launch V2.1. I'll also change the date in the changelog of 2.1 as needed depending on when it gets launched.

**Comment by cloneofghosts** [comment]
@alexander0042 I updated the release date for V2.1 in the docs as it hasn't been launched yet. Is it going to be launched soon or you still need more time for testing? If it needs more time maybe the 2.1 stuff should be hidden for now so people don't get confused that the version number on prod isn't 2.1

**Comment by cloneofghosts** [comment]
Hey @alexander0042 any updates here? Its been almost a week since you merged my last PR with the docs changes and V2.1 hasn't been launched yet which I assume is due to the fact that you're still busy.

**Comment by alexander0042** [comment]
Thanks for the ping! I was about to launch it, but got bogged down doing GEFS checks to make sure the lack of icon isn't the symptom of a larger issue, which took quite a bit of debugging going back to the raw model data. I'm 95% sure it's just a weird interpolation thing, so easy enough to fix in the response code, but it's the sort of clue that I might have done something wrong with the data ingest, and this was my chance to verify it. Fingers crossed it goes live tomorrow, and from there address the other urgent issues!

**Comment by cloneofghosts** [comment]
> Thanks for the ping! I was about to launch it, but got bogged down doing GEFS checks to make sure the lack of icon isn't the symptom of a larger issue, which took quite a bit of debugging going back to the raw model data.

Ah, ok that makes sense. I was just curious because you added a release date to the docs and then didn't release the update.

> Fingers crossed it goes live tomorrow, and from there address the other urgent issues!

Most of the issues tagged as urgent are issues that should be fixed once V2.1 releases. The only one not related to that is open sourcing the API code which is something you're working on. There's a few issues tagged as high priority which should be looked at next and also should look at anything tagged as 'Needs Review' in this and the HA repo.
 
> Great idea with the private repo, and I'll start uploading stuff there soon! Now that everything is a bunch of docker containers, it's semi-feasible to run on a local machine (RAM permitting), which would be pretty cool!

All that's in the repo currently is just a placeholder readme file so feel free to go and add/change whatever you'd like. I won't make it public until you're ready to release the code publicly. Do you want me to create an issue there with some things to look at before making it public? Would be stuff like adding a license, issue templates, etc.

**Review by alexander0042 — APPROVED** [review]

**Comment by cloneofghosts** [comment]
Oh, awesome. I'm still seeing V2.0.11 when I query the API so is it still rolling out?

**Pull request merged**
