### PR TITLE
2.4.1 docs

### LINKED ISSUE #11: Self Hosting Questions
Many thanks for the project and open sourcing your processing scripts.
I tried to dabble a bit myself before finding this project and only got as far as extracting and looking at the data in the grib files.
I was able to run the docker with your included scripts to download the data from s3 onto my machine.

*Building*
```
cd pirateweather/wgrib2/
docker build -t wgrib2 -f Dockerfile .
docker image list
```
*Running*
```
docker run --net=host \
    -v "D:\\WEATHER\\:/mnt" \
    -e bucket="noaa-hrrr-bdp-pds" \
    -e download_path="/mnt/data/efs1z" \
    -e temp_path="/mnt/data/tmp" \
    -e time="2022-12-30T15:45:00Z" \
    wgrib2 \
    /mnt/pirateweather/scripts/hrrrh_combined-fargate.py
```

I have a couple questions.
1. The timestamp input seems to determine the times that are downloaded, how do you normally specify this? The current time?
2. Do I need to run all scripts? or since I am in the US, can I just run the HRRR which I believe has most data (you note on the docs it doesn't seem to have UV, but that is ok for me currently).
3. If I need to run the other scripts, can this be done concurrently, or just sequentially?
4. The [example run command](https://gallery.ecr.aws/j9v4j3c7/pirate-wgrib2) puts files inside a `efs1z` folder. Is this a specific folder name? or does it have some meaning here? Should the other scripts be in a different folder?
5. I want to run the download on a cron job, could you explain how I should interpret this [trigger table](https://docs.pirateweather.net/en/latest/#trigger)? Should I run HRRR every hour to get data, or just every 3 hours could suffice?

The one code I am trying to find is what maps the lat, lon to query these files. The docs say that this is a lambda function that does this and is relatively detailed on the process. Is this code public? If so could you point me in the right direction? Many thanks!

### LINKED ISSUE #360: Relative humidity values can exceed 100%
### Describe the bug

As shown in [this comment](https://github.com/Pirate-Weather/pirate-weather-ha/issues/330#issuecomment-2439904606) relative humidity can exceed 100% when it should not be possible to do so.

### Expected behavior

Humidity should not be able to exceed 100%

### Actual behavior

Humidity can exceed 100%

### API Endpoint

Production

### Location

Romania

### Other details

I would also check to make sure relative humidity cannot go below 0% and other data points to make sure they have a minimum/maximum value where it makes sense. An example would be to make sure cloud cover cannot exceed 1 or go below 0.

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### LINKED ISSUE #363: Apparent temperature calculation incorrect
### Describe the bug

Was looking through the code yesterday to see if relative humidity was capped at 100% (see #360) I noticed that the apparent temperature formula you have is slightly incorrect.

Basically you either need to separate out the formula for calculating water vapor pressure or add brackets around it and should be setup as below:

`AT = Ta + 0.33 × (rh / 100 × 6.105 × exp(17.27 × Ta / (237.7 + Ta))) − 0.70 × ws − 4.00`

How its setup now I believe it leads to the apparent temperature being lower than it should be but cannot confirm.

### Expected behavior

Apparent temperature calculation has brackets around the water vapor pressure formula

### Actual behavior

Apparent temperature calculation is missing brackets around the water vapor pressure formula

### API Endpoint

Production

### Location

Not applicable

### Other details

@alexander0042 This is a good case for the source code to be available. I know you want to try an optimise it more but you could always release as is and add it afterwards? Not sure what the plan is for that as I haven't seen an updated timeline anywhere.

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### LINKED ISSUE #367: Weather alert new lines added in middle of sentences
### Describe the bug

Newlines were recently added to weather alerts. They are added in the middle of sentences where they shouldn't be.

### Expected behavior

I expect the text to have each section separated by newlines, but not wrap early.

```
"* WHAT...Visibility Below One Half Mile In Dense Fog.

* WHERE...Portions Of Northwest And West Central Iowa, Southwest Minnesota, And Central, East Central, South Central, And Southeast South Dakota.

* WHEN...Until 10 AM CST This Morning.

* IMPACTS...Low Visibility Could Make Driving Conditions Hazardous."
```

`Southwest Minnesota ... Southeast South Dakota`

### Actual behavior

Example:

```
"* WHAT...Visibility Below One Half Mile In Dense Fog.

* WHERE...Portions Of Northwest And West Central Iowa, Southwest
Minnesota, And Central, East Central, South Central, And Southeast
South Dakota.

* WHEN...Until 10 AM CST This Morning.

* IMPACTS...Low Visibility Could Make Driving Conditions Hazardous."
```

`Southwest \n Minnesota ... Southeast \n South Dakota`

It's like the text is wrapped at a certain column, but since websites are dynamically sized, this wouldn't look good if I replaced the newlines with `<br>`, because the lines would be in the wrong place.

### API Endpoint

Production

### Location

Sioux Falls, SD

### Other details

_No response_

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### LINKED ISSUE #368: Hourly windBearing can be less than 0
### Describe the bug

Hourly windBearing can be less than 0

### Expected behavior

Hourly windBearing should be between 0-360

### Actual behavior

windBearing = -18.0 for 41.883,-87.632 at 2024-11-08 19:00:00 -0600

### API Endpoint

Production

### Location

41.883,-87.632

### Other details

_No response_

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### LINKED ISSUE #369: Day summary/icon incorrect
### Describe the bug

This morning I noticed a few instances where the day icon and summary aren't being calculated correctly. Examples below:

Today
```
  "icon": "clear-day",
  "summary": "Clear",
  "precipIntensity": 0,
  "precipIntensityMax": 0,
  "precipProbability": 0.05,
  "precipAccumulation": 0,
  "cloudCover": 0.4,
```

Tuesday
```
  "icon": "clear-day",
  "summary": "Clear",
  "precipIntensity": 0.0161,
  "precipIntensityMax": 0.0468,
  "precipProbability": 0.44,
  "precipAccumulation": 0,
  "cloudCover": 0.38,
```

Wednesday
```
  "icon": "partly-cloudy-day",
  "summary": "Partly Cloudy",
  "precipIntensity": 0.0326,
  "precipIntensityMax": 0.2587,
  "precipProbability": 0.22,
  "precipAccumulation": 0.0698,
  "cloudCover": 0.37,
```

### Expected behavior

Today and Tuesday should show Partly Cloudy as the summary and icon. Wednesday should show Clear as the summary and icon.

### Actual behavior

Today and Tuesday shows Clear as the summary and icon. Wednesday shows Partly Cloudy as the summary and icon.

### API Endpoint

Production

### Location

Barrhaven, Ontario

### Other details

This isn't related to the icon issue but I noticed that Tuesday has a `precipIntensity` above zero whereas the `precipAccumulation` is 0. I thought it would be above zero in this case.

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have not included my API key anywhere in my issue.
- [X] I have written an informative title.

### PR DESCRIPTION
**Pull request by cloneofghosts**
## Describe the change
Updates the API docs for version 2.4.

## Type of change

- [ ] Updated Home Assistant documentation
- [ ] General documentation updates (fixing typos, updating information, etc.)
- [ ] Added item to who is using section
- [x] Updated docs for new API version release

## Checklist

- This pull request fixes issue: fixes #11, fixes #368, fixes #363, fixes #360, fixes https://github.com/Pirate-Weather/pirate-weather-ha/issues/330 and fixes #367 
- [x] Update OpenAPI spec
- [ ] Update API documentation
- [x] Update recent updates section
- [x] Update changelog
- [x] Update roadmap
- [x] Update data sources page

### CODE REVIEW

**Comment by alexander0042** [comment]
Thanks again for making this checklist, it makes it so much easier to keep track of things! I'll work away at it and check things off as I go

**Comment by cloneofghosts** [comment]
Did a few more updates here:

- Updated README
- Updated OpenAPI spec
- Updated recent updates
- Updated roadmap
- Remove old processing scripts

You'll want to double check and make sure everything is good before merging this in. I updated the recent updates section with a copy of the changelog but it looks to be slightly outdated. Don't see the alert change in there or if #360 or #369 will be fixed before launch.

**Comment by cloneofghosts** [comment]
@alexander0042 I saw that in the changelog the release date for V2.4 is supposed to be today. Is that still the plan or do we need to update the launch date in the changelog?

**Comment by alexander0042** [comment]
That was the goal, but I really want to get issue #360 integrated, since it's some pretty low hanging fruit. Didn't quite make the Friday deadline, but I should have a chance to put it in this weekend! It'll be a series of np.clip functions, so conceptually pretty simple, but just a lot of code coverage

**Comment by alexander0042** [comment]
Also hoping to get Issue #369 in as well! It's a variable swap, so know what needs to be done, and should be really doable

**Comment by cloneofghosts** [comment]
@alexander0042 Updated the docs for V2.4.1. Is this good to merge in and can we make the code repository public or not yet?

If we can make it public then I'll add a link to the repo when creating a new issue.

**Review by alexander0042 — APPROVED** [review]

**Comment by alexander0042** [comment]
Yes on both counts! We're good to merge, and I'll flip the code repo over to public now! I want to more documentation on how to actually run it and finish the repo setup stuff before I blast it out on the e-mail list, but no reason not to soft launch it

**Pull request merged**
