### PR TITLE
Update V2.3 Changelog

### LINKED ISSUE #130: TimeMachine data only available before May 2023
### Describe the bug

The documentation says that the time machine cannot be used for historic data _within the last 5 days_, and to use the forecast API instead.

Because "the last five days" isn't exactly defined, I want to make sure I can build in error handling.

If I try to hit the forecast API with a date that's too far in the past, it gives me a 400 Bad Request with the body `"Requested time too early, please use https://timemachine.pirateweather.net"`.  Great!

However, if I try to hit the time machine API with a date that's too recent, it gives me a 502 with the body
```json
{
	"message": "Bad Gateway",
	"error": "could not JSON decode Lambda function response: statusCode validation failed"
}
```

### Expected behavior

I would expect hitting the time machine API with a date that's too recent would return a 400 Bad Request, ideally with the latest timestamp that would be available on the time machine, but just a 400 would be fine too.

### Actual behavior

Instead, I see an opaque 502 that suggests that an upstream service is returning an error.

### API Endpoint

TimeMachine

### Location

42.794697,-71.357407

### Other details

Sample requests (requests made today, 24 December, around noon (1700UTC)

- forecast call that correctly 400s (1 Dec 23:59 ET is before "5 days ago") `https://api.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-02T04:59:59Z`
- time machine call that I believe should 400, but instead 502s (since 22 Dec 23:59 ET is within 5 days) `https://timemachine.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-23T04:59:59Z`
- time machine call that works normally, since it's far enough in the past `https://timemachine.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-02T04:59:59Z`

Also, would it be possible to clarify when exactly the cutoff for "last 5 days" is?  Is it based on UTC midnight?  Or the location midnight?  Or exactly (current date - 5*24h)?

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #314: Support putting the API key in the request header, rather than the URL.
### Describe the feature

The documentation says to keep the API key secret. However, requiring the API key to be in the URL makes that difficult, as request URLs show up frequently in logs and error messages, which risks exposure of the API key in various places. Ideally, you would accept a header like

```
api-key: 1234567890
```

If this is already supported in some way, it should be documented.

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the feature has already been requested.
- [X] I have written an informative title.

### LINKED ISSUE #316: Can only get last 32 hours data using the API endpoint
### Describe the bug

According to the [documentation](https://pirateweather.net/en/latest/API/#time-machine-request) you should be able to get the last three days worth of data using the API endpoint and after that you need to use the timemachine endpoint.

### Expected behavior

Should be able to query data from the last three days using the API endpoint

### Actual behavior

Can only query up to the last 32 hours of data before getting a "Requested time too early, please use https://timemachine.pirateweather.net" error message

### API Endpoint

Production

### Location

Ottawa, Ontario

### Other details

@alexander0042 Is the API endpoint only going to store the last 32h of data now? If so then we need to update the docs to reflect the change

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #318: Internal Server when using coordinates outside the maximum longitude/latitude
### Describe the bug

As noted [here](https://github.com/Pirate-Weather/pirateweather/issues/315#issuecomment-2330206714) if you use coordinates which contain values outside the maximum longitude or latitude the API returns an Internal Server Error instead of 400 Bad request

### Expected behavior

The API returns an Internal Server Error

### Actual behavior

The API should return 400 Bad Request Error instead

### API Endpoint

Production

### Location

91,181

### Other details

If you query the API using characters instead of numbers it returns 400 Bad Request (such as using x,x)

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### PR DESCRIPTION
**Pull request by cloneofghosts**
Updates the V2.3 changelog and

- Fix #130
- Fix #318 
- Fix #316 
- Fix #314

### CODE REVIEW

**Comment by cloneofghosts** [comment]
@alexander0042 Noticed that I'm getting a mix of V2.2 and V2.3 at times. You still working on solving the issues with the Time Machine update?

**Comment by alexander0042** [comment]
Yea, I kept hitting this irritating memory leak in xarray with async, which wasn't an issue until timemachine. This kept killing the container, so I was stuck with a solid one running 2.2 and an unstable one running 2.3. Good news is that it's finally fixed, so switching both instances over to v2.3 soon!!

**Comment by cloneofghosts** [comment]
Nice. You going to take care of updating the docs for V2.3? The changelog the date needs updated and the conflict in the OpenAPI spec is because I updated the current one to have the error codes.

I think updating the time machine section and adding the docs for the API key in request header is all that's needed.

**Comment by cloneofghosts** [comment]
@alexander0042 I updated the API docs to add the updated Time Machine/API key information and is now ready for review. There are a few conflicts which need fixing (I can do that if you like) but otherwise just check to make sure the info I added is correct (I mainly used your comments in the issues for the information)

**Comment by cloneofghosts** [comment]
I decided that it would be better to just merge this PR in for now and you can always update the information as needed afterwards.

**Pull request merged**
