### PR TITLE
Update timemachine changelog, docs and add response headers/error codes

### LINKED ISSUE #130: TimeMachine data only available before May 2023
### Describe the bug

The documentation says that the time machine cannot be used for historic data _within the last 5 days_, and to use the forecast API instead.

Because "the last five days" isn't exactly defined, I want to make sure I can build in error handling.

If I try to hit the forecast API with a date that's too far in the past, it gives me a 400 Bad Request with the body `"Requested time too early, please use https://timemachine.pirateweather.net"`.  Great!

However, if I try to hit the time machine API with a date that's too recent, it gives me a 502 with the body
```json
{
	"message": "Bad Gateway",
	"error": "could not JSON decode Lambda function response: statusCode validation failed"
}
```

### Expected behavior

I would expect hitting the time machine API with a date that's too recent would return a 400 Bad Request, ideally with the latest timestamp that would be available on the time machine, but just a 400 would be fine too.

### Actual behavior

Instead, I see an opaque 502 that suggests that an upstream service is returning an error.

### API Endpoint

TimeMachine

### Location

42.794697,-71.357407

### Other details

Sample requests (requests made today, 24 December, around noon (1700UTC)

- forecast call that correctly 400s (1 Dec 23:59 ET is before "5 days ago") `https://api.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-02T04:59:59Z`
- time machine call that I believe should 400, but instead 502s (since 22 Dec 23:59 ET is within 5 days) `https://timemachine.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-23T04:59:59Z`
- time machine call that works normally, since it's far enough in the past `https://timemachine.pirateweather.net/forecast/REDACTED/42.794697,-71.357407,2023-12-02T04:59:59Z`

Also, would it be possible to clarify when exactly the cutoff for "last 5 days" is?  Is it based on UTC midnight?  Or the location midnight?  Or exactly (current date - 5*24h)?

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #314: Support putting the API key in the request header, rather than the URL.
### Describe the feature

The documentation says to keep the API key secret. However, requiring the API key to be in the URL makes that difficult, as request URLs show up frequently in logs and error messages, which risks exposure of the API key in various places. Ideally, you would accept a header like

```
api-key: 1234567890
```

If this is already supported in some way, it should be documented.

### Acknowledgements

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the feature has already been requested.
- [X] I have written an informative title.

### LINKED ISSUE #316: Can only get last 32 hours data using the API endpoint
### Describe the bug

According to the [documentation](https://pirateweather.net/en/latest/API/#time-machine-request) you should be able to get the last three days worth of data using the API endpoint and after that you need to use the timemachine endpoint.

### Expected behavior

Should be able to query data from the last three days using the API endpoint

### Actual behavior

Can only query up to the last 32 hours of data before getting a "Requested time too early, please use https://timemachine.pirateweather.net" error message

### API Endpoint

Production

### Location

Ottawa, Ontario

### Other details

@alexander0042 Is the API endpoint only going to store the last 32h of data now? If so then we need to update the docs to reflect the change

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #318: Internal Server when using coordinates outside the maximum longitude/latitude
### Describe the bug

As noted [here](https://github.com/Pirate-Weather/pirateweather/issues/315#issuecomment-2330206714) if you use coordinates which contain values outside the maximum longitude or latitude the API returns an Internal Server Error instead of 400 Bad request

### Expected behavior

The API returns an Internal Server Error

### Actual behavior

The API should return 400 Bad Request Error instead

### API Endpoint

Production

### Location

91,181

### Other details

If you query the API using characters instead of numbers it returns 400 Bad Request (such as using x,x)

### Troubleshooting steps

- [X] I have searched this repository and [Home Assistant Repository](https://github.com/alexander0042/pirate-weather-ha) to see if the issue has already been reported.
- [X] I have read through the [API documentation](https://pirateweather.net/en/latest/API/) before opening this issue.
- [X] I have written an informative title.

### LINKED ISSUE #320: Pricing/limit needs to be updated
### Describe the issue

The old limit is still listed:

> Anything helps, and a $2 monthly donation lets me raise your API limit from 20,000 calls/ month to 25,000 calls per month.

### Documentation URL

https://docs.pirateweather.net/en/latest/Blog/indexv01/

### Acknowledgements

- [X] I have searched this repository to see if the issue has already been reported.
- [X] I have written an informative title.

### PR DESCRIPTION
**Pull request by cloneofghosts**
- Updates the Time Machine changelog and API docs to fix #130 and fix #316
- Adds Response Headers and Error codes section as per #315
- Updates the docs and fix #314 
- Adds in more models to the roadmap as per #207
     -  This also adds RRFS/3D-RTMA/3D-URMA to the roadmap even though the stable version is not out yet
- Update the calls on index pages and fix #320 
- Also fixes #318

Before this can be merged the Time Machine changelog will need its date added.

### CODE REVIEW

**Comment by cloneofghosts** [comment]
Do you want to add the X-FORECAST-API-CALLS as described in https://github.com/Pirate-Weather/pirateweather/issues/315 so we can close that issue as well when this gets merged in?

**Comment by alexander0042** [comment]
Thanks for pulling this all together! Just writing up the changelog, then I'll push a commit!

**Comment by cloneofghosts** [comment]
Alright, cool. Should probably look over my other changes to make sure everything else is correct and should add to the documentation about adding the key to the request header.

**Comment by alexander0042** [comment]
Pulling this update for tonight to correctly roll back to v2.2, so we can just leave this as a branch for now. There seems to be some sort of memory overload with the timemachine update, but it happens even when there's no requests to that endpoint, so just really strange. I'll get things stable for now, then figure out what's up tomorrow!

**Comment by cloneofghosts** [comment]
Okay, sounds good. Maybe this PR should be split into two so some of the changes can be made while you figure out the V2.3 issue?

**Comment by alexander0042** [comment]
I'm 80% sure it's a small fix- I think it's just a case of not clearing variables at the end of a response, so hoping it's just some del statements and we'll be good to go! Unrelated, but thanks again for highlighting that NCAR S3 archive! I don't know why it's not highlighted more, since it was exactly the sort of thing that's perfect for this application

**Pull request closed without merging**
